// Code generated by MockGen. DO NOT EDIT.
// Source: foo.go
//
// Generated by this command:
//
//	mockgen -source=foo.go Interface
//
// Package mock_main is a generated GoMock package.
package mock_main

import (
	context "context"
	reflect "reflect"

	runtime "github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	v4 "github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/containerservice/armcontainerservice/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// BeginAbortLatestOperation mocks base method.
func (m *MockInterface) BeginAbortLatestOperation(ctx context.Context, resourceGroupName, resourceName, agentPoolName string, options *v4.AgentPoolsClientBeginAbortLatestOperationOptions) (*runtime.Poller[v4.AgentPoolsClientAbortLatestOperationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginAbortLatestOperation", ctx, resourceGroupName, resourceName, agentPoolName, options)
	ret0, _ := ret[0].(*runtime.Poller[v4.AgentPoolsClientAbortLatestOperationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginAbortLatestOperation indicates an expected call of BeginAbortLatestOperation.
func (mr *MockInterfaceMockRecorder) BeginAbortLatestOperation(ctx, resourceGroupName, resourceName, agentPoolName, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginAbortLatestOperation", reflect.TypeOf((*MockInterface)(nil).BeginAbortLatestOperation), ctx, resourceGroupName, resourceName, agentPoolName, options)
}
